### ISSUE TITLE
Current block todo

### ISSUE THREAD

**Issue by Waterpicker** [GenerationsMod/Generations-Core#17]
- [x] HDTV
- [x] Bush
- [x] Desk
- [ ] Work Desk
- [x] Couch
- [ ] Bookshelf
- [ ] Shelf
- [x] Wooden Bench
- [x] Pokeball Floor Cushion
- [x] Swivel Chairs
- [x] Rotom PC
- [x] Table PC
- [x] Litwick Candle
- [x] Litwick Candles

Couch
- - [x] Couch Arm Left
- - [x] Couch Arm Right
- - [x] Couch Corner Left
- - [x] Couch Corner Right
- - [x] Couch Middle
- - [x] Couch Ottoman

- [x] AZ Flabebe Flower
- [ ] Egg Inclubator
- [x] Scarecrow

- [x] Black Street Lamp
- [x] White Street Lamp
- [x] Double Street Lamp

Shop DIsplay
- - [ ] Shop Shelf 1
- - [ ] Shop Shelf 2
- - [ ] Shop Round Shelf 1
- - [ ] Shop Round Shelf 2
- - [ ] Shop Case 1
- - [ ] Shop Case 2

- [x] Pokeball Pillar
- [ ] Fridge
- [x] Elevator
- [x] Box
- [x] Trash Can

**Comment by JT122406** [comment]
Leave Cool Stone stuff out for now I am gonna make some decisions on it
